import type { PaymentSummary, WithdrawalRequest } from './types';

export const paymentSummaries: PaymentSummary[] = [
  {
    id: 'total-revenue',
    label: 'Total Revenue',
    value: '\u20a61.5M',
    helperText: 'Vs Previous month',
    helperTone: 'positive',
  },
  {
    id: 'client-revenue',
    label: 'Revenue Generated (Clients)',
    value: '\u20a6800k',
    helperText: 'Vs Previous month',
    helperTone: 'positive',
  },
];

export const withdrawalRequests: WithdrawalRequest[] = [
  {
    id: 'withdrawal-1',
    dueDate: 'Apr 26, 2026',
    transactionDate: 'Jul 29 2025, 10:57AM',
    transactionId: 'TMR07890J',
    receiverName: 'Henry Osuji',
    receiverEmail: 'henryjr9@gmail.com',
    status: 'pending',
    currentBalance: 1200000,
    amountRequested: 400000,
    totalFee: 0,
    description: '-',
    receiverDetails: {
      accountName: 'OSUJI HENRY CHIBUIKEM',
      accountNumber: '1234567890',
      bankName: 'Bank of HNG',
    },
  },
  {
    id: 'withdrawal-2',
    dueDate: 'May 3, 2026',
    transactionDate: 'Jul 30 2025, 9:22AM',
    transactionId: 'XPL45612B',
    receiverName: 'Amara Nwosu',
    receiverEmail: 'amara.nwosu@example.com',
    status: 'in_progress',
    currentBalance: 1500000,
    amountRequested: 400000,
    totalFee: 0,
    description: '-',
    receiverDetails: {
      accountName: 'NWOSU AMARA CHIDINMA',
      accountNumber: '2023456781',
      bankName: 'Bank of HNG',
    },
  },
  {
    id: 'withdrawal-3',
    dueDate: 'May 10, 2026',
    transactionDate: 'Aug 1 2025, 2:15PM',
    transactionId: 'QZN34987K',
    receiverName: 'Chinedu Okeke',
    receiverEmail: 'chinedu.okeke@example.net',
    status: 'completed',
    currentBalance: 1800000,
    amountRequested: 400000,
    totalFee: 0,
    description: '-',
    receiverDetails: {
      accountName: 'OKEKE CHINEDU',
      accountNumber: '3023456782',
      bankName: 'Bank of HNG',
    },
  },
  {
    id: 'withdrawal-4',
    dueDate: 'May 17, 2026',
    transactionDate: 'Aug 3 2025, 11:40AM',
    transactionId: 'VBG23015M',
    receiverName: 'Ngozi Eze',
    receiverEmail: 'ngozi.eze@example.org',
    status: 'on_hold',
    currentBalance: 2000000,
    amountRequested: 400000,
    totalFee: 0,
    description: '-',
    receiverDetails: {
      accountName: 'EZE NGOZI',
      accountNumber: '4023456783',
      bankName: 'Bank of HNG',
    },
  },
  {
    id: 'withdrawal-5',
    dueDate: 'May 24, 2026',
    transactionDate: 'Aug 6 2025, 3:04PM',
    transactionId: 'HCD98147W',
    receiverName: 'Emeka Obi',
    receiverEmail: 'emeka.obi@example.co',
    status: 'completed',
    currentBalance: 2300000,
    amountRequested: 400000,
    totalFee: 0,
    description: '-',
    receiverDetails: {
      accountName: 'OBI EMEKA',
      accountNumber: '5023456784',
      bankName: 'Bank of HNG',
    },
  },
  {
    id: 'withdrawal-6',
    dueDate: 'May 24, 2026',
    transactionDate: 'Aug 7 2025, 8:32AM',
    transactionId: 'HCD98148X',
    receiverName: 'Emeka Obi',
    receiverEmail: 'emeka.obi@example.co',
    status: 'declined',
    currentBalance: 2300000,
    amountRequested: 400000,
    totalFee: 0,
    description: '-',
    receiverDetails: {
      accountName: 'OBI EMEKA',
      accountNumber: '5023456784',
      bankName: 'Bank of HNG',
    },
  },
  {
    id: 'withdrawal-7',
    dueDate: 'May 26, 2026',
    transactionDate: 'Aug 9 2025, 4:17PM',
    transactionId: 'AKL56290Q',
    receiverName: 'Tobi Adeyemi',
    receiverEmail: 'tobi.adeyemi@example.com',
    status: 'pending',
    currentBalance: 1100000,
    amountRequested: 350000,
    totalFee: 0,
    description: '-',
    receiverDetails: {
      accountName: 'ADEYEMI TOBI',
      accountNumber: '6023456785',
      bankName: 'Bank of HNG',
    },
  },
  {
    id: 'withdrawal-8',
    dueDate: 'May 28, 2026',
    transactionDate: 'Aug 11 2025, 12:05PM',
    transactionId: 'BNS44120P',
    receiverName: 'Ifeoma Udo',
    receiverEmail: 'ifeoma.udo@example.com',
    status: 'completed',
    currentBalance: 2600000,
    amountRequested: 500000,
    totalFee: 0,
    description: '-',
    receiverDetails: {
      accountName: 'UDO IFEOMA',
      accountNumber: '7023456786',
      bankName: 'Bank of HNG',
    },
  },
  {
    id: 'withdrawal-9',
    dueDate: 'Jun 1, 2026',
    transactionDate: 'Aug 13 2025, 10:48AM',
    transactionId: 'RXT90832L',
    receiverName: 'Kunle Balogun',
    receiverEmail: 'kunle.balogun@example.com',
    status: 'on_hold',
    currentBalance: 900000,
    amountRequested: 250000,
    totalFee: 0,
    description: '-',
    receiverDetails: {
      accountName: 'BALOGUN KUNLE',
      accountNumber: '8023456787',
      bankName: 'Bank of HNG',
    },
  },
  {
    id: 'withdrawal-10',
    dueDate: 'Jun 4, 2026',
    transactionDate: 'Aug 15 2025, 1:55PM',
    transactionId: 'MKA75310V',
    receiverName: 'Aisha Bello',
    receiverEmail: 'aisha.bello@example.com',
    status: 'in_progress',
    currentBalance: 1750000,
    amountRequested: 450000,
    totalFee: 0,
    description: '-',
    receiverDetails: {
      accountName: 'BELLO AISHA',
      accountNumber: '9023456788',
      bankName: 'Bank of HNG',
    },
  },
  {
    id: 'withdrawal-11',
    dueDate: 'Jun 7, 2026',
    transactionDate: 'Aug 17 2025, 5:08PM',
    transactionId: 'PLD11890C',
    receiverName: 'Seyi Martins',
    receiverEmail: 'seyi.martins@example.com',
    status: 'declined',
    currentBalance: 650000,
    amountRequested: 200000,
    totalFee: 0,
    description: '-',
    receiverDetails: {
      accountName: 'MARTINS SEYI',
      accountNumber: '1123456789',
      bankName: 'Bank of HNG',
    },
  },
  {
    id: 'withdrawal-12',
    dueDate: 'Jun 10, 2026',
    transactionDate: 'Aug 20 2025, 9:12AM',
    transactionId: 'GHA88720N',
    receiverName: 'Ruth Ibrahim',
    receiverEmail: 'ruth.ibrahim@example.com',
    status: 'pending',
    currentBalance: 3100000,
    amountRequested: 700000,
    totalFee: 0,
    description: '-',
    receiverDetails: {
      accountName: 'IBRAHIM RUTH',
      accountNumber: '1223456780',
      bankName: 'Bank of HNG',
    },
  },
];
